name: Update cloud repo

on:
  schedule:
    # At 08:00 on Sunday
    - cron: "0 8 * * 0"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Single deploy job since we're just deploying
  update-cloud-repo:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          architecture: 'x64'
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run update script
        run: make TOOLSET=cloud update-all && make TOOLSET=cloud fix-no-deps
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            title: Update cloud repo ${{ steps.date.outputs.date }}
            branch: cloud-tool-updates
            branch-suffix: timestamp
